const _deploy_contracts = require("../migrations/2_deploy_contracts");

// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var verifier = artifacts.require("Verifier");

contract("TestSquareVerifier", (accounts) => {
  describe("Check verifier functions", function () {
    beforeEach(async function () {
      this.verifierContract = await verifier.new({ from: accounts[0] });
    });

    // Test verification with correct proof
    // - use the contents from proof.json generated from zokrates steps
    it("Correct Proof", async function () {
      let proofCheck = {
        proof: {
          a: [
            "0x1ba0df5159c4c75da8a30d34e28b0a2242b9634aed77c9b41b979e6081ed5033",
            "0x04a81e18c8c57362b000213bce6d533055ba4f830dc76abf9c5bf37907ffbdd0",
          ],
          b: [
            [
              "0x272c1132c59a11b904df2e3921eaf7b40ce948a1a24e9b36dd6e2e04cc3e9560",
              "0x1535e1e6c5cb4d685ef68595487910d68d8813765f422b977b53e32f8c53fc94",
            ],
            [
              "0x26e8a26d9bd754c038c42bb9b5b32b91a0c1463aba53b03eb8e224f1230f853a",
              "0x2c080f65faca972f26229da56b338fc12d62261f8626ec42659bc1090e7a983d",
            ],
          ],
          c: [
            "0x08c833d09a989255fa84bd16e9b4374fbf2c59f92f8b67298771b72c03e56f7f",
            "0x2f85944aef8c9f217463077e0d8f85fdf5546b3b570820ade0cf9c95a3feb440",
          ],
        },
        inputs: [
          "0x0000000000000000000000000000000000000000000000000000000000000009",
          "0x0000000000000000000000000000000000000000000000000000000000000001",
        ],
        raw:
          "1ba0df5159c4c75da8a30d34e28b0a2242b9634aed77c9b41b979e6081ed5033a72c1132c59a11b904df2e3921eaf7b40ce948a1a24e9b36dd6e2e04cc3e95601535e1e6c5cb4d685ef68595487910d68d8813765f422b977b53e32f8c53fc9488c833d09a989255fa84bd16e9b4374fbf2c59f92f8b67298771b72c03e56f7f",
      };
      let result = await this.verifierContract.verifyTx.call(
        proofCheck.proof.a,
        proofCheck.proof.b,
        proofCheck.proof.c,
        proofCheck.inputs,
        { from: accounts[0] }
      );
      assert.equal(result, true, "Wrong proof!");
    });

    // Test verification with incorrect proof
    it("Wrong Proof", async function () {
      let proofCheck = {
        proof: {
          a: [
            "0x1ba0df5159c4c75da8a30d34e28b0a2242b9634aed77c9b41b979e6081ed5033",
            "0x04a81e18c8c57362b000213bce6d533055ba4f830dc76abf9c5bf37907ffbdd0", // I changed something in a to send a wrong proof
          ],
          b: [
            [
              "0x272c1132c59a11b904df2e3921eaf7b40ce948a1a24e9b36dd6e2e04cc3e9560",
              "0x1535e1e6c5cb4d685ef68595487910d68d8813765f422b977b53e32f8c53fc94",
            ],
            [
              "0x26e8a26d9bd754c038c42bb9b5b32b91a0c1463aba53b03eb8e224f1230f853a",
              "0x2c080f65faca972f26229da56b338fc12d62261f8626ec42659bc1090e7a983d",
            ],
          ],
          c: [
            "0x08c833d09a989255fa84bd16e9b4374fbf2c59f92f8b67298771b72c03e56f7f",
            "0x2f85944aef8c9f217463077e0d8f85fdf5546b3b570820ade0cf9c95a3feb440",
          ],
        },
        inputs: [
          "0x0000000000000000000000000000000000000000000000000000000000000009",
          "0x0000000000000000000000000000000000000000000000000000000000000002", //I changed something here to provide a wrong proof
        ],
        raw:
          "1ba0df5159c4c75da8a30d34e28b0a2242b9634aed77c9b41b979e6081ed5033a72c1132c59a11b904df2e3921eaf7b40ce948a1a24e9b36dd6e2e04cc3e95601535e1e6c5cb4d685ef68595487910d68d8813765f422b977b53e32f8c53fc9488c833d09a989255fa84bd16e9b4374fbf2c59f92f8b67298771b72c03e56f7f",
      };
      //   try {
      let result2 = await this.verifierContract.verifyTx.call(
        proofCheck.proof.a,
        proofCheck.proof.b,
        proofCheck.proof.c,
        proofCheck.inputs,
        { from: accounts[0] }
      );
      //   } catch (error) {
      //     console.log(error);
      //   }
      assert.equal(result2, false, "Correct proof!");
    });
  });
});
